const likeSongList =
    [
        {
            "id": -1,
            "subscribers": [],
            "subscribed": false,
            "name": "我喜欢的音乐",
            "creator":
            {
                "defaultAvatar": false,
                "province": 1000000,
                "authStatus": 0,
                "followed": false,
                "avatarUrl": "",
                "accountStatus": 0,
                "gender": 1,
                "city": 1000100,
                "birthday": 0,
                "userId": -1,
                "userType": 0,
                "nickname": "",
                "signature": "",
                "description": "",
                "detailDescription": "",
                "avatarImgId": 109951166380171400,
                "backgroundImgId": 3241360282584965,
                "backgroundUrl": "",
                "authority": 0,
                "mutual": false,
                "expertTags": [],
                "experts": {},
                "djStatus": 0,
                "vipType": 0,
                "remarkName": null,
                "authenticationTypes": 0,
                "avatarDetail": {
                    userType: -1,
                    identityLevel: 0,
                    identityIconUrl: ""
                },
                "avatarImgIdStr": "109951166380171386",
                "backgroundImgIdStr": "3241360282584965",
                "anchor": false,
                "avatarImgId_str": "109951166380171386"
            },
            "specialType": 0,
            "createTime": -1,
            "highQuality": false,
            "artists": null,
            "tracks": null,
            "playCount": 0,
            "updateFrequency": null,
            "backgroundCoverId": 0,
            "backgroundCoverUrl": null,
            "titleImage": 0,
            "titleImageUrl": null,
            "englishTitle": null,
            "opRecommend": false,
            "recommendInfo": null,
            "subscribedCount": 0,
            "cloudTrackCount": 3,
            "userId": -1,
            "totalDuration": 0,
            "coverImgId": 109951165443368140,
            "privacy": 0,
            "trackUpdateTime": -1, "trackCount": 0,
            "updateTime": 1674315161014,
            "commentThreadId": "A_PL_0_138379329",
            "coverImgUrl": "",
            "sharedUsers": null,
            "shareStatus": null,
            "copied": false
        }
    ]
export default likeSongList